### ISSUE TITLE
All links to D365 Retails are inaccessible as of 2:00pm EST October 1st 2019

### ISSUE THREAD

**Issue by anytranya** [MicrosoftDocs/feedback#1989]
**Describe the bug**
All links to D365 Retails are inaccessible as of 2:00pm EST October 1st 2019

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dynamics365/
2. Click on Retail\Documentation
3. See error

**Expected behavior**
All pages have to be loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/56044305/65988081-2d027680-e455-11e9-8a87-0f4c7b0d7299.png)

![image](https://user-images.githubusercontent.com/56044305/65988356-a8642800-e455-11e9-9165-991e88e4346a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Additional context**
Did try to access from many zones, servers, regions, either from Microsoft cloud server, from America to Asia. All are failed to access.

**Comment by mairaw** [comment]
@buck1ey Can you look at this issue reported for the Dynamics 365 docs homepage?

My link checker tool also flagged this link in the bottom as broken:
![image](https://user-images.githubusercontent.com/12971179/65990095-cb83dd00-e43f-11e9-94b8-d69b43e0d10b.png)

**Comment by KumarVivek** [comment]
@mairaw We fixed the on-premises link and are working on fixing others as well. Thanks!

**Comment by diamond911** [comment]
Me too.

**Comment by v-iliva** [comment]
https://docs.microsoft.com/en-us/dynamics365/outlook-app/deploy-dynamics-365-app-for-outlook

In this section the link is not working as well:

![image](https://user-images.githubusercontent.com/53929549/66031220-a361b000-e50b-11e9-9ba9-36789498758e.png)

**Comment by rsammut** [comment]
Still inaccessible...

![image](https://user-images.githubusercontent.com/18441609/66043739-41f80c00-e520-11e9-87ab-52eeff7975c3.png)

**Comment by anytranya** [comment]
Retails document links are still not working. I have task to deliver this week :( 
Hopefully it is fixed ASAP. 
Do MS have any backup link? if so, please provide. Thank you.

**Comment by dendeli-msft** [comment]
Thank you all for the feedback! Closing this issue as the links are working correctly now.
