### ISSUE TITLE
https://docs.microsoft.com/en-us/learn - change email address

### ISSUE THREAD

**Issue by AndreasManzke** [MicrosoftDocs/feedback#998]
Hello,
I have changed the primary email address for my Microsoft account. With this account I logged in at https://docs.microsoft.com/en-us/learn . Now I can't log in to Microsoft Learn with this account anymore, because it want to create a new techprofile. If I want to create this profile, I get the message "You are already registered".
Thanks for the help.
Andreas

**Comment by saldana** [comment]
@Sampy this seems the same than https://github.com/MicrosoftDocs/feedback/issues/1014, when the user changes the e-mail address after creating a tech profile, they cannot sign in into MS Learn. Is this a bug in our system?

**Comment by Sampy** [comment]
We are working on a fix for this issue now and hope to have it out this week or next.

**Comment by Sampy** [comment]
We have deployed a change that should fix this issue. It may take some time to roll out to you so try it again and let me know if you are still hitting the problem. If so, there may be another cause we need to look into.

**Comment by AndreasManzke** [comment]
Today I tried to login and it's working. Thanks

**Comment by Sampy** [comment]
Excellent. Thanks for reporting the issue.

**Comment by MIMostafa** [comment]
I’m having a similar issue. Every time I go to Microsoft Learn and try to create a tech profile, I click on Register and nothing happens. It literally stays on the same page. I tried lots of things but I’m stuck on create profile. For example I intentionally try to put a too short url, I get the error it is too short. Once I put a long enough URL, error disappears but still unable to move past the register stage. 

Can you help please??

**Comment by MIMostafa** [comment]
Just found out that it doesn’t work when country is United Kingdom. I tried IS as country and I managed to create a profile!

**Comment by saldana** [comment]
@jialge  can you look into this issue? I am reopening so it stays in your radar.
